# revprox450
version: "3.6"

services:
  #1
  vpv445gb:
    # 192.168.88.60:6216
    image: nginx:1.14-alpine
    ports:
      - "80:80"
      - "443:443"
    # expose:
    #   - "8083"
    volumes:
      - ./docker/nginx_vpv445g/nginxmain.conf:/etc/nginx/nginx.conf
      - ./docker/nginx_vpv445g/default.conf:/etc/nginx/conf.d/default.conf
    restart: always



